---
title:  Regular expressions  
teaching: 15
exercises: 20
objectives:
- "Describe the difference between a text string and a regex pattern"
- "Use helper function `str_detect()` to find text"
- "Find a simple exact match in a vector"
keypoints:
- "Regular expressions are the way we can describe text patterns to a computer"
- "Patterns can match either exact text or text that meets certain criteria"
- "The `str_detect()` function will search for a regex pattern within a text vector"
- "`.` is a wildcard pattern"
source: Rmd
---

## Describing text to computers

Regular expressions are the language ...

> ## Other approaches
> There may be alternative approaches that can also achieve the same result. Think about those 
> alternatives as you work through these challenges and consider whether regular expressions are 
> the best option.
> {Insert "I used regex to solve a problem ..."}
{: .callout}

> ## Fruit data
> Vectors and text...
> How many fruit?
{: .challenge}

## How to find a fruit

Compare with Find in Excel
Want to find 'apple', how can R help us - `str_detect()`

> ## Kicking the str_detect tyres
> Run the following commands, what is the output and why?
> (match multiple with full words, match a substring, fail to match with capitals, throw in a space?)
> Write a str_detect command to find these fruits:
{:. challenge}

## Not just exact matches

The power in regular expressions comes from...

> ## Specific currants
> In words, how could we find just the 'blackcurrant' and 'redcurrant' from the fruits, while not detecting the plain 'currant'? 
{: .challenge}

## Wildcards

regex patterns have many special characters that are not matched exactly..

'.currant'

> ## What value?
> What are the potential benefits/problems with this method?
> Reproducible, repeatable, extensible, recorded. Complex, extensible? 
{: .discussion}

## Regex in data frames
Usually, have data in data frames. Remember about columns being stored as vectors, so can use these
regex functions on columns of a data frame (eg. within mutate)

Eg of this (first w/ mutate, then with filter)

> ## Fruit frames
> make a fruit data frame, using the regex patterns for currants above, filter the df to 1) all currants
> 2) all specific currants
{: .challenge}
